require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'weightress' do
  use_modular_headers!
  # "use_frameworks!"
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  # pod 'WatermelonDB', :podspec => '../node_modules/@nozbe/watermelondb/WatermelonDB.podspec', :modular_headers => true

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  target 'weightressTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.2'
      end
    end
    # flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end

target 'NotebookShareExtension' do
  # use_react_native!
  use_modular_headers!
  # "use_frameworks!"
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  # Manually link packages here to keep your extension bundle size minimal
end

target 'weightress-tvOS' do
  # Pods for weightress-tvOS

  target 'weightress-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
